import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header style={{ position: "fixed", top: 0, width: "100%" }} />
        <div
          style={{ paddingTop: "60px", paddingBottom: "60px" }}
          className="flex flex-col min-h-screen "
        >
          <main className="flex-1 container mx-auto px-1 py-5">{children}</main>
        </div>
        <Footer style={{ position: "fixed", bottom: 0, width: "100%" }} />
      </body>
    </html>
  );
}
