import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <main className="flex-1 container mx-auto px-1 py-5">{children}</main>
        </div>

        <footer className="py-4">
          <div className="text-center">
            (c) {new Date().getFullYear()} MatsBACCANO
          </div>
        </footer>
      </body>
    </html>
  );
}
